version: '3.8'

services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_DB: exa-data
      POSTGRES_USER: exa-data
      POSTGRES_PASSWORD: exa-data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 -q -U exa-data"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  db.test:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_DB: exa-data-test
      POSTGRES_USER: exa-data
      POSTGRES_PASSWORD: exa-data
    ports:
      - 5433:5432

  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    depends_on:
      db:
        condition: service_healthy
